# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bspline_basis_cpp <- function(x, i, order, knots) {
    .Call(`_cubicSpline_bspline_basis_cpp`, x, i, order, knots)
}

